site_name: Otterdog configuration @ eclipse-tractusx
site_description: Otterdog configuration @ eclipse-tractusx
strict: true

site_url: https://eclipse-tractusx.github.io/.eclipsefdn/

docs_dir: ./docs
site_dir: ./_site

theme:
  name: 'material'
  custom_dir: docs/overrides

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - macros

nav: []
watch: []
