site_name: Otterdog configuration @ eclipse-tractusx
site_description: Otterdog configuration @ eclipse-tractusx
strict: true

site_url: https://eclipse-tractusx.github.io/.eclipsefdn/

docs_dir: ./docs
site_dir: ./_site

theme:
  name: 'material'

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins: []
nav: []
watch: []
